[package]
name = "unsigned-varint"
version = "0.3.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
description = "unsigned varint encoding"
repository = "https://github.com/paritytech/unsigned-varint"
readme = "README.md"
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[features]
codec = ["bytes", "tokio-util"]
futures-codec = ["bytes", "futures_codec"]

[dependencies]
bytes = { version = "0.5.3", optional = true }
futures = { version = "0.3.4", optional = true }
futures_codec = { version = "0.3.4", optional = true }
tokio-util = { version = "0.2", features = ["codec"], optional = true }

[dev-dependencies]
criterion = "0.3"
hex = "0.4"
quickcheck = "0.9"
tokio-util = { version = "0.2", features = ["codec"] }

[[bench]]
name = "benchmark"
harness = false
